# This is an example configuration
[network]
bind = "127.0.0.1"
port = 25565
compression_threshold = 256

[server_info]
motd = "Some Random MOTD which is configurable."

[players]
type = "Constant"
players = 1337
max_players = 210
fail_on_over_join = true